### ISSUE TITLE
Improvements for the new Relicans page

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1079]
https://developer.newrelic.com/relicans

The follow improvements are suggestions by the DevEx team to ensure this page confirms to our style guide and code standards. 

### Feedback

1. Work with a product designer such as @djsauble for feedback on this page to improve the overall look and feel of the page.
2. consider the following suggestions to improve the code of this page:

- [x] Left align the "Meet the Relicans" header
- [ ] Suggest making the intro paragraphs use the same <intro> component that are found on other overview pages (e.g. collect data). 
- [x] The individual profile tiles aren't well-anchored in space, there's a lot of jagged whitespace because of their differing heights. Consider giving each tile a border of some kind? (but without a drop shadow so they don't look like clickable tiles, the way other tiles on the site are clickable)

**Comment by jpvajda** [comment]
@caylahamann could you provide some suggestions and I can pass these along the Dev Rel team?

**Comment by caylahamann** [comment]
I think I fixed most of the changes that meet our code standards. I think the best process would be: 
1. Get design feedback 
2. Implement the design changes 
3. Do another thorough code review 

Most of the suggestions I have currently are just designed based, but I don't really have the answers. I think we should try to fix the spacing and alignment of the profiles for one.

**Comment by jpvajda** [comment]
@caylahamann let's ask @djsauble for his input on this page, though technically I think he's just providing his design services on the Docs site until Go live, so maybe he'll be willing to provide some suggestions for this page.

**Comment by jpvajda** [comment]
Introducing @aaronbassett to @djsauble to perhaps get some design suggestions on for this page.

**Comment by jpvajda** [comment]
moving to the contributor project, as it's no longer a devex team task

**Comment by djsauble** [comment]
This looks pretty good! From a design perspective, I only have a few suggested tweaks:

1. Left align the "Meet the Relicans" header
2. Suggest making the intro paragraphs use the same "18px and grey" styling that are found on other overview pages (e.g. [collect data](https://developer.newrelic.com/collect-data)). That said, this would also need to be applied to the [Developer champions](https://developer.newrelic.com/developer-champion), [New Relic Builders](https://developer.newrelic.com/builders), and [Podcasts](https://developer.newrelic.com/podcasts) pages for consistency.
3. The individual profile tiles aren't well-anchored in space, there's a lot of jagged whitespace because of their differing heights. Consider giving each tile a border of some kind? (but without a drop shadow so they don't look like clickable tiles, the way other tiles on the site are clickable)

**Comment by rudouglas** [comment]
@jpvajda i've made the recommended changes to the `Meet the Relicans` title and put a border around each relicans tile. #1287 should cover the points **_1 and 3_**.

The only question I have is on the styling of the Intro sections. I've tested styling the entire Intro `18px and grey` on each page and on the `Relicans` page it looks a bit more clumsy, maybe because there's no darker paragraph below the intro to provide that contrast. 

### Relicans
![Screenshot Mon, April 26, 2021 12_36_49](https://user-images.githubusercontent.com/17122543/116380759-2e03b180-a80c-11eb-81bd-966435e4c7ef.png)

However there does seem to be inconsistency with how this is applied across the whole site for example:

 - Whole Intro - https://developer.newrelic.com/build-apps/map-pageviews-by-region
 - Part Intro - https://developer.newrelic.com/collect-data/custom-attributes
 - None - https://developer.newrelic.com/automate-workflows/diagnose-problems

Should we decide on a style and I can do a review of each page and make the relevant changes?

**Comment by rudouglas** [comment]
### Meet the Relicans changes 

![Screenshot Mon, April 26, 2021 12_37_19](https://user-images.githubusercontent.com/17122543/116415332-3ae6cc00-a831-11eb-8b9d-69fcb5831370.png)

**Comment by jpvajda** [comment]
@rudouglas so I think what you can do here is: apply the <Intro> component to the Relican page and those pages you noticed that were inconsistent. The [component](https://github.com/newrelic/developer-website/blob/29a067249fd29a8fff799ded968f464542e9d4be/src/components/Intro.js#L6) was designed (_for the dev site only_) to style the introduction of a guide. I think it would work well in this case.

**Comment by jpvajda** [comment]
@rudouglas I actually broke out the consistency stuff into another issue, if you want to take this for your onboarding that is cool with me 😎 

https://github.com/newrelic/developer-website/issues/1288

**Comment by rudouglas** [comment]
@jpvajda awesome thanks, since we've moved `Intro` changes to a separate issue, should we remove action point 2 from this and look to close it out?

**Comment by jpvajda** [comment]
@rudouglas for this page, I'd say wrapping that paragraph text on this page in the <intro> component is a good change and we can do that.

**Comment by rudouglas** [comment]
Great, i've added the Intro to that page so #1290 should finish the last action point on this 👯
