### ISSUE TITLE
Relative links from embed pages don't work

### ISSUE THREAD

**Issue by alexronquillo** [newrelic/developer-website#1227]
### Bug

When I click a relative link from an `/embed` page, I get a 404.

### Anything else you'd like to share?

Expected behavior:

1. Navigate to https://developer.newrelic.com/build-apps/ab-test/demo-setup
2. Click the relative link in the intro callout
3. You navigate to the correct page

Actual behavior:

1. Navigate to https://developer.newrelic.com/build-apps/ab-test/demo-setup/embed/
2. Click the relative link in the intro callout
3. You get a 404

**Comment by jpvajda** [comment]
This seems like a worthy thing to improve on, so for now I'll slot it into Sprint 2  not sure of the effort and the 2nd part of the issue feels more like an enhancement since the original work was about embedded guide pages, not embedded index pages, as I believe that's a different template. We may want to break this ticket up, unless the work is related.
