### ISSUE TITLE
Empty ".extended-webpackrc.js" in "Map page views by region in a custom app"

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/developer-website#1326]
### Tell us what you need

Most (all?) of the `.extended-webpackrc.js` collapsers in this doc are empty. https://developer.newrelic.com/build-apps/map-pageviews-by-region/ Not sure if these should just be deleted or if there's content that should be added.

### Doc information (don't delete this section)

* https://developer.newrelic.com/build-apps/map-pageviews-by-region/
* **OS**: Mac OS 10.15.7
* **Browser**: Edge 90.0.818.66
* **Device**: Unknown

**Comment by jpvajda** [comment]
I wouldn't consider this a bug, more so a documentation style choice. given we are displaying the 3 files used in this tutorial consistently across each step, I think it's fine to include the tab view of each file, so it's clear that nothing changes in this file in certain steps.  I feel it clearly allows a person to know when something changes  / not changes. but I'll ping @alexronquillo on this for a 2nd opinion here.  😄

**Comment by alexronquillo** [comment]
@austin-schaefer @jpvajda  tldr; This is intentional, and I recommend leaving it as is.

This guide uses the [`<Tutorial>` component](https://github.com/newrelic/developer-website/blob/develop/COMPONENT_GUIDE.md#tutorial), which provides some nice features like file tabs, auto-highlighting, etc. With it, the author establishes, at the top of the piece, a `<Project>` that includes all the files that'll be edited throughout the course of the guide. In this case, that's three files including `.extended-webpackrc.js`. 

There are trade-offs to consider for this approach vs the traditional approach of using manual codeblocks and highlighting. So we have to decide what's the best UX.

The options here are:

1. Leave it as is.
2. Separate `.extended-webpackrc.js` from the `<Project>` and have that be its own separate codeblock that only shows up in that step. The other two files would remain in the `<Project>` and would have a different UX.

Most of the benefits of `<Tutorial>` don't apply to `.extended-webpackrc.js` as it only changes once where it goes from no content to final content. However, as @jpvajda mentioned, there is the benefit of consistently showing the three working files throughout the piece. In particular, for steps after that file has content, readers can tab over and see the current state of every file.

I think that the benefits of consistency and grouping the files together outweigh the weirdness of having that file be empty for most of the piece, especially because it reflects the real file state.

However, I think if you want to create a dev issue that addresses the limitation of showing new files later in a guide, I'd support that. There are many cases where that would be beneficial. This is one. Another case would be if the user needed to create a new file in a project half-way through the guide. There's no way to do that now.

**Comment by jpvajda** [comment]
Reading the docs on the <Tutorial> component I can see several improvements we could make to this component to offer more flexibility when build guides with steps and code files. But, it's not really a priority for us at the moment to make improvements how the component works. I'd vote we just close this issue out, leave it the way it is, and measure if we get other reports of confusion or problems from actual users. AFAIK, we haven't had an external reports from users of issues with this approach.
