### ISSUE TITLE
[Gatsby Cloud]  DNS Changes and Documentation Updates: Dev Site

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1338]
### Related Issue

JIRA: `ELB-1682` `DONE`

https://github.com/newrelic/developer-website/issues/1270

###  Acceptance Criteria 

- [x] Leave Amplify connected the repository
- [x] move the DNS entry over to Gatsby Cloud --> need to work with `ELB`
- [x] also move the SSL cert --> need to work with `ELB`
- [ ] Publish any documentation changes (troubleshooting, architecture, etc)
- [ ] Remove Amplify webhook
- [ ] Remove GH/Amplify integration

**Comment by aswanson-nr** [comment]
I feel like the harbinger of bad news for this effort.

[Fastly limits apex domains to one account](https://support.gatsbyjs.com/hc/en-us/articles/1500003204562-I-m-receiving-an-error-from-Fastly-so-how-do-I-resolve-that-). For example:
Account 1 has `foo.example.com` and `example.com`. Account 2 attempts to use `bar.example.com` and is unable to do so. This is because Account 1 owns `*.example.com`.

We have 2 possible solutions:
1. Ask if there is a possible work around - JIRA / ELB-1602
2. [Integrate Gatsby Cloud with the existing Fastly account](https://support.gatsbyjs.com/hc/en-us/articles/360053098873-Deploying-to-Fastly)

**Comment by jpvajda** [comment]
blocked on the issue with sub-domains on Fastly which Gatsby is working on for June. Ticket TBD.

**Comment by aswanson-nr** [comment]
CNAME transfer ticket `ELB-1682`
