### ISSUE TITLE
Replace screenshots in overview with logo files

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1365]
The current use of screen shots in the catalog view of the Olly packs should use the logo file not the screenshot as this is a better indicator to a user of what the pack is for.

<img width="1398" alt="Screen Shot 2021-06-03 at 3 45 53 PM" src="https://user-images.githubusercontent.com/1395158/120716283-0fd04780-c483-11eb-91b0-4937efb6c331.png">

### Acceptance Criteria

- [x] Use the logo file in place of the screen shot for a pack.
- [x] if the pack contains no logo file, (_as it's optional in the pack config)_ default to a default logo of New Relic

**Comment by rudouglas** [comment]
Using logos instead of Dashboard images, uses NR logo if no logo is present:

<img width="1120" alt="Screenshot 2021-06-04 at 16 50 59" src="https://user-images.githubusercontent.com/17122543/120829605-80e02f80-c555-11eb-8c88-441475d6c752.png">
<img width="1092" alt="Screenshot 2021-06-04 at 16 51 07" src="https://user-images.githubusercontent.com/17122543/120829610-82115c80-c555-11eb-9b85-f44f1099ff9c.png">

**Comment by jpvajda** [comment]
CRUSHING IT... 😍

**Comment by jpvajda** [comment]
LOL Couchbase.. 🛋️

**Comment by rudouglas** [comment]
CouchPotato 🥔
