### ISSUE TITLE
UI Nits for O11y packs: Public Library

### ISSUE THREAD

**Issue by aswanson-nr** [newrelic/developer-website#1375]
# Summary
Various nit picks for the o11y pack public library. We'll discuss each one at the end of the Public Catalog Epic and decide which to do and turn them into individual issues if required. 

* The search bar does not display an `X` button to clear the text.
https://github.com/newrelic/newrelic-observability-packs/issues/61

* Fade the gallery image on the right hand side. (See the FIMGA design for example)

https://github.com/newrelic/newrelic-observability-packs/issues/60

* add a Arrow button to move through the gallery so it's clear this is gallery component.

https://github.com/newrelic/newrelic-observability-packs/issues/59

* add a default logo image css treatment so each logo has a more consistent appearance in the pack library view. (may need design input)
 
> skip  

* add a default logo for packs without logos. (probably a new relic image)

> this will be merged in with a change ruairi made. 

* add a default images for packs without  screenshots , etc. 

> skip

* I'm noticing is that some of the pack logos are svgs and don't render properly., ensure they are rendering OK

https://github.com/newrelic/newrelic-observability-packs/issues/58

* On smaller screen sizes (width: 2500px-ish) the pack grid extends past the search and filter bars on the right. Fix this so that the grid aligns with the search/filter bars 

https://github.com/newrelic/newrelic-observability-packs/issues/57

**Comment by jpvajda** [comment]
I've asked @danielgolden about moving the install button down to the right rail info section...waiting on feedback

**Comment by jpvajda** [comment]
Daniel made a great point on why the install button is where it is: 

"The primary reason it’s been moved is because when a users switches tabs, the content of that right column would change. For example, if I click the “dashboards” tab, then the right column is probably going to go away entirely because it’s not directly related to the dashboards, it’s more general. Even if we were to keep the right column in the dashboards view (though really this applies to any other tab except “overview”) then the context of the tab muddies the waters of what exactly you’re “installing”. If I’m in the dashboards tab then it suggests maybe I’m just installing the dashboards. By moving it above the tabs we no longer have issues with context because it is clearly an installation of the pack not the contents of whatever tab is active."

**Comment by jpvajda** [comment]
break into tickets for each of these.

**Comment by jpvajda** [comment]
closing this round of nits all issues have been discussed and filed accordingly
