### ISSUE TITLE
[Public Catalog] Browser back button does not work on Observability Pack landing page

### ISSUE THREAD

**Issue by zstix** [newrelic/developer-website#1475]
### Description

When viewing the [Obserability Pack landing page](https://observabilitypacks.gatsbyjs.io/observability-packs), the browser back button does not work. Clicking it appears to briefly adjust the URL, but the page doesn't change.

### Steps to reproduce

1. Go to https://observabilitypacks.gatsbyjs.io (Developer site homepage on the feature branch).
2. Click on 'Observability packs' in the left sidebar.
3. Click on the browser back button.

### Expected behavior

The browser back button should take the user to the previous page.

### Additional context

My _guess_ as to why this is happening is due to how the url is structured on the page. There is a `/` between the URL and the `?params`. When you go to the landing page, navigation happens that redirects the browser to a _new_ page (`url/?params`). When the user tries to go "back" they're just going back to the index page (`url/`).

To fix this, we should be settings params without an extra slash: `url?params`.

### Acceptance Criteria 

- [x] The browser back button should work in all cases

**Comment by zstix** [comment]
Note: this may no longer be an issue when we migrate to Gatsby Cloud (due to the trailing slash).

**Comment by rudouglas** [comment]
I timeboxed this and couldn't figure out a workaround so we may want to just move this and recheck after we've moved to Gatbsy cloud

**Comment by aswanson-nr** [comment]
It looks like this is related to the page messing with the query parameters without setting the browser history. To set the browser history we need to change up the way it works a bit, instead of using hooks to immediately re-render the page on a change, we need to use `navigate` from `@reach/router` like the attribute dictionary on the docs-site.

Proposed new render flow:
1. Check for query parameters
2. If there are parameters, filter the list of packs

Proposed new filtering flow:
1. Update a filter
2. Click `search` (would need to add a search button)
3. Collect the new parameters
4. Navigate to the new parameters (this would then lead into the flow above)

@jpvajda  This proposal requires us to add a `search` button to trigger the search, instead of it being immediate. If we want search to still happen automatically, we will need to discuss how that will work.

**Comment by jpvajda** [comment]
@aswanson-nr why can't this work like our global search where we don't ask a user to click "search"?

**Comment by jpvajda** [comment]
Moving to the epic that will deal with turning the packs into a stand alone gatsby site.
