### ISSUE TITLE
Move dev-site `only` components to the Gatsby Theme

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1476]
To prepare for some content migration work planned by the Dev Advocacy team we want to move the dev site only components used for building the guides into the docs site so guides can be created on that site property.

### References 

- [Dev Site Component Guide](https://github.com/newrelic/developer-website/blob/develop/COMPONENT_GUIDE.md)

### Acceptance Criteria

- [ ] All DevSite components used in guides are migrated to the gatsby theme for use on the Docs Site
- [ ] By doing this change, existing guides on the Dev Site should still work. 
- [ ] Bump the dev site to the new Gatsby theme. 
- [ ] Bump the Docs site to the new Gatsby Theme.
- [ ] Bump the OSS site to the new Gatsby Theme.
- [ ] When complete confirm with @jaesius and @alexronquillo so they can start their content  migration work.

**Comment by jpvajda** [comment]
@jaesius and @alexronquillo let me know how this sounds...

**Comment by jpvajda** [comment]
I spoke to @zstix about this as well, he's going to review this ticket.

**Comment by zstix** [comment]
I think this could end up being a pretty sizable effort. There are [_a lot_](https://github.com/newrelic/developer-website/tree/develop/src/components) of components in the developer site repository that haven't been brought into the theme; mostly because they're only used in one place: the developer site.

While we wont be able to move _everything_ over, I believe that the intention of this ticket is to move all components responsible for rendering authored content (guides) into the theme so that we can more freely move content around. Please feel free to correct me if that's the wrong assumption.

Here's are the components in the developer-website repository that _could_ be moved into the theme to help facilitate our IA adjustments

| Component | SWAG Estimation | Notes |
| - | - | - |
| [`Agenda`](https://github.com/newrelic/developer-website/tree/develop/src/components/Agenda) | `sp:3` | We may want to keep this in the developer repository. This needs a refactor (which would bump it to a `sp:5`). |
| [`CodeDef`](https://github.com/newrelic/developer-website/tree/develop/src/components/CodeDef) | `sp:5` | Only has value if we bring in the other platform-component-related components. |
| [`Countdown`](https://github.com/newrelic/developer-website/tree/develop/src/components/Countdown) | `sp:3` | Straightforward. Could use a refactor along the way though. |
|  [`CodeEditor`](https://github.com/newrelic/developer-website/blob/develop/src/components/CodeEditor.js) | `sp:3` | This is already in the theme, we just need to update the references. |
| [`GuideListing`](https://github.com/newrelic/developer-website/tree/develop/src/components/GuideListing) | `sp:2` | Straightforward. |
| [`Caution`](https://github.com/newrelic/developer-website/blob/develop/src/components/Caution.js) | `sp:3` | Should be refactored to use existing components. |
| [`ExternalLink`](https://github.com/newrelic/developer-website/blob/develop/src/components/ExternalLink.js) | `sp:2` | We should just use what's in the theme for this. |
| [`FunctionDefinition`](https://github.com/newrelic/developer-website/blob/develop/src/components/FunctionDefinition.js) | `sp:5` | Only has value if we bring in the other platform-component-related components. |
| [`HideWhenEmbedded`](https://github.com/newrelic/developer-website/blob/develop/src/components/HideWhenEmbedded.js) | `sp:5` | A little bit of work to bring in the context stuff too, but well worth it (IMO). |
| [`IconGallery`](https://github.com/newrelic/developer-website/blob/develop/src/components/IconGallery.js) | `sp:3` | A couple of files for this. Not sure how much value it would provide to be in the theme. |
| [`Intro`](https://github.com/newrelic/developer-website/blob/develop/src/components/Intro.js) | `sp:5` | I'd like to see a refactor of `SideBySide` as part of this work |
| [`PropList`](https://github.com/newrelic/developer-website/blob/develop/src/components/PropList.js) | `sp:5` | Only has value if we bring in the other platform-component-related components. |
| [`ReferenceExample`](https://github.com/newrelic/developer-website/blob/develop/src/components/ReferenceExample.js) | `sp:5` | Could even be an `sp:8`. Only has value if we bring in the other platform-component-related components. |
| [`Spinner`](https://github.com/newrelic/developer-website/blob/develop/src/components/Spinner.js) | `sp:2` | Straightforward. |
| [`Tutorial`](https://github.com/newrelic/developer-website/blob/develop/src/components/Tutorial.js) | `sp:5` | I don't know what this is for, but it looks heavy. |
| [`Video`](https://github.com/newrelic/developer-website/blob/develop/src/components/Video.js) | `sp:2` | We already have this in the theme, should be able to remove it here. |

If my math is correct, that's `58` points which would take us [about two weeks](https://www.youtube.com/watch?v=YZ4z0QhD92Y). There may be some hidden work in there as well (hooks, converting CSS modules to emotion, etc.).
