### ISSUE TITLE
search bar filters all show `0` after filtering packs

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1490]
### Steps to repro 

- select an item to filter the packs by, 
- view the filter counts
- they are all 0 now 🤷 

### screen shot

<img width="1347" alt="Screen Shot 2021-07-20 at 4 15 03 PM" src="https://user-images.githubusercontent.com/1395158/126402609-91a0c5ca-cd24-49ee-9ac2-20c2716a216d.png">

### Expected 

when filtering counts should reflect actual counts per filter item.

**Comment by rudouglas** [comment]
This was changed as part of one of the nits, we talked about changing that number depending on the filter, so if a filter resulted in `3 results`, `2` of which have Dashboards and `1` of which have Alerts it would show

```
All (3)
Dashboards (2)
Alerts (0)
```

Which is why it's showing `0` here, because there are `0` results from your filtering. This is probably not a great approach, i think we should keep those numbers as totals and then just let `Showing X results` display the subset of results, or even remove those numbers altogether, i don't think we need both

**Comment by jpvajda** [comment]
ah I see it makes a lot more sense when looking at apache.. I think this works and once we have more pack components it should be a better exp..  I close for now.

<img width="1382" alt="Screen Shot 2021-07-21 at 10 11 55 AM" src="https://user-images.githubusercontent.com/1395158/126522877-6f63857f-728f-47ac-9377-d3d1c130082f.png">
