### ISSUE TITLE
[Dev Site] Audit browser PageAction events to make sure the Wiki is up to date

### ISSUE THREAD

**Issue by rudouglas** [newrelic/developer-website#1805]
### Description

The Browser agent PageAction events in the wiki seem to be out of date, we will need to go through the events we are creating using `useInstrumentedHandler` and `useInstrumentedData` hooks and make sure all the new I/O events are added to the Wiki

#### Useful Links
https://github.com/newrelic/developer-website/wiki/Editing-Event-Data-and-Instrumentation#action-name

### Acceptance Criteria

 - [x] Check all events and enure the wiki reflects what is in the code 
 - [x] Wiki is up to date with the Browser events we are collecting
 - [x] Consider if there is a way to automate this documentation and report back ideas and findings.

**Comment by tabathadelane** [comment]
When using this NRQL query, a lot of the undocumented pageAction names stop being reported over the last few weeks as changes have been made to the code to convert these event to tessen. Similarly, there are a 4 actions that are not being reported at all over the last 60 days, so I have removed them from the wiki. 

the `navInteraction` event seems to be tied to the `navInteractionType` key in `NakLink.js` which is documented under `internalLink_click` & `externalLink_click`.

Regarding the automation, since we are looking to migrate toward tessen events exclusively soon, there seems to be no reason to automate these actions.
