### ISSUE TITLE
[Dev Site] Resolve feather icon deprecations on Dev Site

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1874]
Run the site locally and view the console in the browser you'll see the following errors, pointing to deprecated feather icon names.

### Error 
```
Warning: You are using a feather icon using its deprecated name: 'zap'. Please use the prefixed feather icon name instead: 'fe-zap' 
Warning: You are using a feather icon using its deprecated name: 'box'. Please use the prefixed feather icon name instead: 'fe-box' 
Warning: You are using a feather icon using its deprecated name: 'zap'. Please use the prefixed feather icon name instead: 'fe-zap' 
Warning: You are using a feather icon using its deprecated name: 'box'. Please use the prefixed feather icon name instead: 'fe-box'
Warning: You are using a feather icon using its deprecated name: 'zap'. Please use the prefixed feather icon name instead: 'fe-zap' 
Warning: You are using a feather icon using its deprecated name: 'box'. Please use the prefixed feather icon name instead: 'fe-box'
```

**Comment by jpvajda** [comment]
I saw this in our theme which is saying we should be using the prefix feather icon name.

https://github.com/newrelic/gatsby-theme-newrelic/blob/1302b794fdebb486b35e347a546ed1ffa553553d/packages/gatsby-theme-newrelic/src/components/Icon.js#L18

**Comment by jpvajda** [comment]
so when changing the icon name this is what is occurring, I don't think this message is useful..

```
Warning: You are using a feather icon using its deprecated name: 'fe-zap'. Please use the prefixed feather icon name instead: 'fe-fe-zap' warning.js:34
Warning: You are using a feather icon using its deprecated name: 'fe-box'. Please use the prefixed feather icon name instead: 'fe-fe-box' warning.js:34
Warning: You are using a feather icon using its deprecated name: 'fe-zap'. Please use the prefixed feather icon name instead: 'fe-fe-zap' warning.js:34
Warning: You are using a feather icon using its deprecated name: 'fe-box'. Please use the prefixed feather icon name instead: 'fe-fe-box' warning.js:34
Warning: You are using a feather icon using its deprecated name: 'fe-zap'. Please use the prefixed feather icon name instead: 'fe-fe-zap' warning.js:34
Warning: You are using a feather icon using its deprecated name: 'fe-box'. Please use the prefixed feather icon name instead: 'fe-fe-box'
```

**Comment by jpvajda** [comment]
https://feathericons.com/?query=zap
https://feathericons.com/?query=box

Based on the feather documentation I think we should [remove this message](https://github.com/newrelic/gatsby-theme-newrelic/blob/1302b794fdebb486b35e347a546ed1ffa553553d/packages/gatsby-theme-newrelic/src/components/Icon.js#L18) in our theme. 

I guess it's not clear why we show this message in the local dev enviroment, as the naming convention of the icons seem correct as `zap` and `box`

**Comment by jpvajda** [comment]
@jerelmiller any thoughts on this? You seemed to do some work in this file in the theme where this warning message is set.

**Comment by jerelmiller** [comment]
>  I think we should remove this message in our theme.

Please don't! This is very useful for developers.

One of the changes I made to the icons way-back-when is the ability to add more than 1 icon library to our gatsby theme. Because of this, there is a potential for naming conflicts between 2 icon libraries if they use the same name. To solve that issue, I added prefixes to each icon library to a) make it apparent which icon library is being used and b) avoid those naming conflicts. 

Up to that point, we had assumed all of our icons were going to be feather icons, but we already had production code out the door. To prevent us from needing to stop everything and update to the new names, I added that deprecation message you see above warning you of using the un-prefixed version of the icon.

The goal is to remove those old names altogether, and when that happens, the sites will break if they are not updated. These messages are useful to pinpoint what is using the deprecated names so that we can update them. Once those messages are gone, we can start to remove the old names from the theme.

Does that make sense?

**Comment by jerelmiller** [comment]
You can find a bit more information about the prefixes here: https://github.com/newrelic/gatsby-theme-newrelic/tree/develop/packages/gatsby-theme-newrelic#icon

**Comment by jerelmiller** [comment]
re: https://github.com/newrelic/developer-website/issues/1874#issuecomment-963693543

I see now that you're also mentioning the double prefix there. It looks like that message is [not that smart](https://github.com/newrelic/gatsby-theme-newrelic/blob/1302b794fdebb486b35e347a546ed1ffa553553d/packages/gatsby-theme-newrelic/src/components/Icon.js#L18) and **only** looks to see if there is an icon with that name or not. If you've changed the name but you're still seeing a warning, its likely because those icons are not yet a part of the icon set. You'll need to create the `zap` and `box` icons in the theme, or shadow those icons in the developer site.

**Comment by jpvajda** [comment]
>  its likely because those icons are not yet a part of the icon set.

Let me push up a PR for which I thought I fixed what the message suggested. Feel free to check it out. DevEn has been focused on reducing console errors so I thought this one was my speed... 😄

**Comment by jpvajda** [comment]
Oh I think I got it, the nav.yml file wasn't use the `fe` prefix for the box and zap icons. this PR resolves it correctly, thanks for the helpful tips @jerelmiller  https://github.com/newrelic/developer-website/pull/1876

**Comment by jerelmiller** [comment]
Awesome! Glad to hear it @jpvajda!!
