### ISSUE TITLE
[Public Catalog] Add Crazy egg script to top 6 quickstart details pages

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#1896]
We'd like to add the crazy egg script to the following quickstart details pages in order to better understand where users are interacting with the details page so we can make more informed design decisions on how to best optimize this page.

- Codestream
- Dotnet
- Java
- Apache 
- Php
- Node-js

### Script

```
 <script
          type="text/javascript"
          src="//script.crazyegg.com/pages/scripts/0045/9836.js"
          async="async"
        />
```

### Acceptance Criteria

note: this is script is set in the[ DevSetSEO.js](https://github.com/newrelic/developer-website/blob/e48402439de8bb3c0c9f94f0ce3d07dd2cf7fc9e/src/components/DevSiteSeo.js#L27) component.

~~-  we are seeing an error when loading the crazy egg script on production, we should resolve this.~~
_Moved this AC to a [new ticket.](https://github.com/newrelic/developer-website/issues/1927)_

```
Uncaught Error: CE: multiple userscripts installed
    <anonymous> https://script.crazyegg.com/pages/scripts/0045/9836.js:1
```

- [x] Add the crazy 🥚 script to the quickstart pages listed above
- [ ] When complete notify @legnaleama so he can start evaluating the data for design improvements

**Comment by tabathadelane** [comment]
re: Multiple userscripts error
According to the [crazyegg docs](script.crazyegg.com/pages/scripts), this will not interfere with the data collection and usually happens when there is more than one account tracking the same page. I did not find that to be the case for us. 

<img width="868" alt="Screen Shot 2021-11-29 at 4 27 19 PM" src="https://user-images.githubusercontent.com/47728020/143963577-fcba7b9d-73e0-4026-8a35-c33f1e28f95d.png">

I will keep digging around.

**Comment by jpvajda** [comment]
Interesting, I'm curious to what you find @tabathadelane.

**Comment by tabathadelane** [comment]
We have decided to revisit the `multiple userscript` error in a [later ticket.](https://github.com/newrelic/developer-website/issues/1927)
