### ISSUE TITLE
Provide last update on each page of the DevEx Site

### ISSUE THREAD

**Issue by caylahamann** [newrelic/developer-website#317]
### Description

As a user I would like to know when a page was last updated so it’s clear to me the recent update of content.

### Acceptance Criteria 

- a new section is added to the bottom of the page above the site footer
- add page last modified {month, day, year}  to each page on the site. this indicates the last time the page was updated

**Comment by caylahamann** [comment]
@djsauble do you have any ideas for the design of this? I would assume it's on every page in the footer

**Comment by djsauble** [comment]
I spent a few minutes playing with this. One thing we could do is differentiate between page-specific actions (e.g. edit this page, view history) above the footer separator and general actions (e.g. terms of service, create an issue) below the footer separator. In particular, "View history" is new but would link to the latest diff of the current page on GitHub (I added because it looked a bit bare to only have the "Edit this page" action above the separator, but we could skip if it's too difficult to implement or if @jpvajda disagrees).

<img width="1297" alt="image" src="https://user-images.githubusercontent.com/186715/86943143-edab3980-c0fa-11ea-92ca-462eebbb9793.png">

**Comment by jpvajda** [comment]
@djsauble If view history isn't a lot of effort I think it's cool to have it especially for guides, as if they have a version that someone may have been using, perhaps they'd want to look at an older version of the page.

**Comment by jpvajda** [comment]
Daniel and I decided to just go with the page last modified time stamp after we discussed this.

**Comment by djsauble** [comment]
Updated mock

<img width="1296" alt="Screen Shot 2020-07-08 at 9 54 33 AM" src="https://user-images.githubusercontent.com/186715/86947784-1c2c1300-c101-11ea-9aa8-03ab976cb615.png">

**Comment by caylahamann** [comment]
@djsauble thank you! Implementing this now :)
