### ISSUE TITLE
Add an Introduction to NewRelic Page

### ISSUE THREAD

**Issue by caylahamann** [newrelic/developer-website#320]
### Description 
As part of the intro to the site for a user who may not be familiar with New Relic it would be nice to have a New Relic Overview Page, and also have this in the primary navigation.

### Acceptance Criteria 

0. This page will need a design as it's slightly different from other pages we have on the site today. 
0. This will need some marketing language which we can source from existing materials we have.
1. Add a Navigation item: New Relic One 
2. Place Nav item at the top of the Side Nav 
3. Build a content page that explains what New Relic is at a high level.

**Comment by jpvajda** [comment]
This will need a design @djsauble would you be able to provide?

**Comment by djsauble** [comment]
@jpvajda I'd like some idea of the content you want here (even a draft) before we decide to go with the full page. I still think augmenting the landing page with this information would flow better and force us to be a bit more concise than we otherwise would be.

**Comment by jpvajda** [comment]
@djsauble sure thing. This is definitely not a super high priority at this moment, so let's just backlog and take our time with it.

**Comment by austin-schaefer** [comment]
One thing to note is that docs (and .com) sites have existing pages for both ["What is New Relic"](https://docs.newrelic.com/docs/using-new-relic/welcome-new-relic/get-started/introduction-new-relic) and ["What is New Relic One"](https://docs.newrelic.com/docs/new-relic-one/use-new-relic-one/get-started/introduction-new-relic-one). For a dev.newrelic.com version, I'd say we'd want to focus on what is New Relic _for people extending New Relic_, rather than a more general "here's what New Relic is and what it can do for you."
