### ISSUE TITLE
[Stretch] On iOS, the global navigation can be "pulled" over the site content

### ISSUE THREAD

**Issue by caylahamann** [newrelic/developer-website#327]
### Description 
When "pulling" down on a page to trigger a refresh, you can pull the global navigation (top-bar) off the top of the page and over the main content area. See attached screenshot. 
![image2](https://user-images.githubusercontent.com/38332422/86055263-7bb36000-ba29-11ea-920f-6417537b0797.jpeg)

### Steps to Reproduce: 
1. Go to the site on a iOS device 
2. Pull down on the page as if to refresh it

### Expected Result
The top-bar should be locked to the top. When pulling down on the page to refresh, the whole page should be pulled down.

**Comment by honeyd** [comment]
Other comments here: https://newrelic.atlassian.net/browse/DEVEX-1084

**Comment by zstix** [comment]
We were able to find a fix (linked draft PR) but it degraded the experience for most users in order to solve a minor issue for a few on mobile.

After speaking with Jerel and Daniel we have decided to punt on this. I'm going to close the PR and remove the release from this issue, but keep it open for now. This may not be a big enough issue that it's worth resolving at the moment.

**Comment by jpvajda** [comment]
I'll tag it as p4, seems super nuanced, and not worth all the effort to try to figure out the issue. If it gets more traction from users we can re-prioritize later.
