### ISSUE TITLE
Route all www.developer.newrelic.com > developer.newrelic.com

### ISSUE THREAD

**Issue by honeyd** [newrelic/developer-website#364]
When a user goes to www.developer.newrelic.com we should route them to developer.newrelic.com so they always find the site they are looking for.

Acceptance Criteria

determine if it’s possible to redirect all www.developer.newrelic.com traffic to developer.newrelic.com 

Reference

https://www.netlify.com/blog/2017/02/28/to-www-or-not-www/
* Talk to the ELB team

**Comment by jpvajda** [comment]
Since the attempt to do this let to a brief outage, we discovered the follow:

None of these sites do the DNS routing from www.  so it seems it's a higher level new relic domain question and is out of scope for our team. 

https://www.docs.newrelic.com/
https://www.discuss.newrelic.com/
https://www.opensource.newrelic.com/

So if we want this experience, we'll have to request this work from the ELB team or some other website team that may be able to facilitate this. for now we'll just backlog this issue for future reference.

**Comment by jpvajda** [comment]
Marking as won't do. We may decide to this later.
