### ISSUE TITLE
Casing standard and name conventions should match the in Product exp.

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#561]
Follow the pattern defined in the in product exp. for search results.

### AC 
- Use all caps in the text of the label  developer = DEVELOPER
- Use the correct naming convention "community" = "discuss"

**Comment by jpvajda** [comment]
after comparing the 2 experiences and thinking about this change to color of the labels, I personal don't think the site needs to color code the labels, I actually like the consistency of all the labels looking similar, @djsauble  what do you think?

**Comment by djsauble** [comment]
It's neat to see this visualized, and I agree. The color draws too much attention to the badge.

We _could_ have a more subtle treatment here though. For example, we want to prioritize links to results on the current site (to keep from bouncing people unnecessarily and also because they're likely on the current site because it's providing value to them), so the badge for those links could be teal and all other badges could be grey.

**Comment by jpvajda** [comment]
Per our conversation today we will hold off on any color changes to the labels and stick with a more consistency design style.

**Comment by jerelmiller** [comment]
Note: This should be done in both the global search and the right rail component
