### ISSUE TITLE
 Implement a marketing banner component for the DevSite & OSS Sites

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#615]
We'll want to provide a banner element component so we can highlight events like nerd days. The banner should be something that a marketer can easily update with a PR to change the content or links. 

**Design Considerations**

- A user should be able to easily submit a PR to update text and links for the component 
- The banner should be able to be closed by a user
- If available we should follow a corporate design for banner elements as input to our approach.
- However, the look and feel for this banner element should be in the DevEx style.   

**Acceptance Criteria**

- This should be designed as a reusable component that can be used on the OSS and Dev Site
- Banner height should be 90px and the height should be easy to configure if we wish to change it.
- Banner should be mobile-responsive.
- There must be a way to dismiss the banner (via a “Dismiss” link in the top-right corner)
- The banner should scroll with the page so it’s not fixed in view the entire time someone is browsing the site.
- If a banner is present, the global header should scroll and pin itself to the top.

**Mock up**

![banner](https://user-images.githubusercontent.com/1395158/90317894-ac702b80-dee9-11ea-98e5-5055a097047b.jpg)

**Comment by zstix** [comment]
I estimated this at 5 points with the following thought process about how this feature _could_ work:

* We have a component on the site that looks at the content of a configuration file (maybe `yaml`)
* The configuration file can specify a date range, text, link, and some style options
* If the current date is within the date range, the component will show the banner

This would allow content contributors to easily add a banner and give them the ability to schedule it for a specific time window. In order to keep the scope of this manageable, we may have to limit the amount of style flexibility we can provide.

**Comment by jerelmiller** [comment]
Finished in #722
