### ISSUE TITLE
scaling of a browser causes the footer to behave oddly and increase in overall size

### ISSUE THREAD

**Issue by markweitzel** [newrelic/developer-website#631]
There is too much space in the footer when you scale your resolution,  It looks like our layout doesn’t handle this situtation, so for “short” pages, it expands the footer a bit to account for some space

### AC

- Resolve this issue with CSS Grid.

<img width="1920" alt="Automate workflows | New Relic Developers 2020-08-18 15-46-57" src="https://user-images.githubusercontent.com/522116/90558528-38908600-e16a-11ea-8482-646be0f22e3e.png">

**Comment by jerelmiller** [comment]
@markweitzel are you using Chrome? I'm on Firefox and I do not see all that extra space.

**Comment by jerelmiller** [comment]
Actually, this doesn't look like a browser issue. Are you zoomed in/out by chance? I can reproduce the the large spacing when the page is not zoomed at 100%

**Comment by markweitzel** [comment]
Using Chrome. No zoom on the page
<img width="1920" alt="Automate workflows | New Relic Developers 2020-08-18 16-04-59" src="https://user-images.githubusercontent.com/522116/90560104-9b831c80-e16c-11ea-8f75-df5cc1e96230.png">

**Comment by jpvajda** [comment]
@djsauble To this issue to provide his design perspective.

**Comment by jerelmiller** [comment]
I'm having difficulty reproducing this on my machine, both on Chrome and Firefox. I can only seem to reproduce it if I zoom the page out to 80%, but as @markweitzel pointed out, that doesn't seem to be the issue.

I'd like to see if we can diagnose the root cause before we invest too much design work on addressing the spacing, only because any spacing changes may or may not address the underlying issue.

**Comment by jerelmiller** [comment]
Here is what I see in Chrome for that page.

<img width="1913" alt="Screen Shot 2020-08-18 at 4 09 47 PM" src="https://user-images.githubusercontent.com/565661/90574245-45fb3f80-e16d-11ea-9dea-5b6287b21ce6.png">

@markweitzel perhaps you could inspect the DOM to see if there is any weird styling/CSS issue you see that I'm not?

**Comment by jerelmiller** [comment]
The more I look at the screenshots, I do notice that there is a ton more vertical space on the monitor. We have the layout set using CSS grid. I'm wondering if maybe at tall screen sizes, the footer is expanding in odd ways.

**Comment by jpvajda** [comment]
I've never seen it as big as @markweitzel reported either, I just thought the 2REM size may be reduced overall. So unless we want to change the footer size, this may be something that is very specific to his setup.

**Comment by jpvajda** [comment]
Jerel figured it out, AC is updated.

**Comment by jerelmiller** [comment]
Turns out I can reproduce it if I scale my monitor's resolution. You can see in the below screenshot that I've got my resolution set to the 3rd option, and here I can see the footer huge.

<img width="3006" alt="Screen Shot 2020-08-18 at 4 19 29 PM" src="https://user-images.githubusercontent.com/565661/90574865-de45f400-e16e-11ea-9193-2eaf6b7485f5.png">

**Comment by djsauble** [comment]
Nice work tracking this down, that was a tricky edge case. 💯
