### ISSUE TITLE
Set up Split.IO

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#655]
Determine the following:

In order to support our experiment with using split.io for A/B Testing I _think_ we may need to install that Gatsby plugin for this functionality. 

https://www.gatsbyjs.com/plugins/gatsby-plugin-splitio/

We should looking this plugin and how it works with Split.io

**Comment by zstix** [comment]
During the call earlier this week, the split representatives mentioned that the plugin only allows for one static user ID. I'm not seeing that to be the case one way or the other.

Regardless, we can use this ticket for the purpose of "setting up" split (whether that be the plugin or just configuring the account as we need). I pointed it at 2 points because it's fairly straightforward but there may be an instance or two where we need further research.
