### ISSUE TITLE
Check into extremely low bounce rates on the OSS and Developer sites.

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#715]
Currently the Bounce rates for the OSS Site and Developer sites are very low. 

**Developer Site in Aug:** 8.41%  Down from 37.67% in July

**OSS Site in Aug:** 3.98% no July stats as GA wasn't integrated yet.
 
**Question to explore:**
Is something triggering an interaction on pages that is nullify the bounce count, and causing GA to not count a bounce event?

**A Bounce is defined as:**

The percentage of single-page sessions in which there was no interaction with the page. A bounced session has a duration of 0 seconds. 

https://support.google.com/analytics/answer/1009409?hl=en

**Comment by jpvajda** [comment]
@jerelmiller / @zstix  any thoughts on this? I thought maybe the right rail search queries may be impacting actual bounce rates.

**Comment by jerelmiller** [comment]
I'm not sure the right rail would be the culprit here. The search queries are run at build time (on a 24 hour cadence), but that hits the Swiftype API and writes to a JSON file. The right rail is populated by pulling data from that JSON file, which means there isn't any hits to the site.

I know Swiftype indexes every 12 hours, which would provide some of the traffic, though I _think_ JavaScript is disabled in that context, which means GA wouldn't be able to pick up the traffic (unconfirmed on this; this is my hunch.) We'd have to do a bit more digging to see if we can spot why we might be getting low bounce rates.

**Comment by jpvajda** [comment]
@jerelmiller ok thanks for the explanation, it's not super urgent, but would be cool to determine the root cause in the next few weeks as it impacts our OKR metrics, as bounce rate is something we measure ourselves against.

**Comment by jpvajda** [comment]
Current Rates 

Sept 1 - Sept 15:

9.53% Dev Site
3.88% OSS Site

**Comment by tariqahmed** [comment]
I came across this [Article](https://www.analyticsmania.com/post/how-to-fix-low-bounce-rate-in-google-analytics/) that has very concrete technical steps to try sleuthing the situation.

The extensions that they reference in there are pretty nifty, [Google Tag Assistant](https://chrome.google.com/webstore/detail/tag-assistant-by-google/kejbdjndbnbjgmefkgdddjlbokphdefk) and the [DataLayer Inspector](https://chrome.google.com/webstore/detail/adswerve-datalayer-inspec/kmcbdogdandhihllalknlcjfpdjcleom).

Came across some other tools that may help:
https://chrome.google.com/webstore/detail/tag-manager-assistant/oacpegaegonlmnobkoeiiegdccgcmpnj

In taking an initial swag at it - not finding any issues (double tagging, sending subsequent events too fast, etc...).

**Comment by tariqahmed** [comment]
Another idea: Can we add e.g. that Adobe analytics tool to give us another view into bounce rate for comparison purposes?

**Comment by caylahamann** [comment]
Hey @tariqahmed @jpvajda I did some investigating into why this is happening. I found a similar issue on a board that claimed that the issue is likely due to two tracking IDs being created. I used Google Tag Assistant and found that this is true for our website, one coming from our source code and another with an external script. I believe this is coming from having the tracking id being created in the gatsby plugin for google analytics and in the script that we have in our index page.

**Comment by zstix** [comment]
All of the engineers spent a considerable amount of time looking into our analytics this morning and were unable to determine the source of the problem. The two calls to Google Analytics _appear_ to be valid (one to create a connection via `ga.create` and another to send the pageview via `ga.send`).

Without much knowledge about how Google Analytics reports bounce rates, we are out of ideas.

**Comment by jpvajda** [comment]
@zstix  Thanks Perhaps we can open an issue the GA support team. I'll reach out to google.

**Comment by jpvajda** [comment]
I've asked sy jones for input on this problem, as she is a GA expert. Will updated when I have details.

**Comment by jpvajda** [comment]
Joel and I looked at the bounce data per page, and we have a lot of pages that just have 0% bounce rates. The component pages are just one example. so I think the data is correct.  

The OSS site has a lot of project pages with 0% bounce rate  which seems to be causing the lower rates. So for now this issue is closed and we are assuming the data is correct.
