### ISSUE TITLE
Investigate Light House performance issues

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#795]
When running a lighthouse test found in Chrome Developer Tools, the test reported very poor performance for developer.newrelic.com opensource.newrelic.com

### Steps to reproduce 

CLI: https://github.com/GoogleChrome/lighthouse

1. Open Chrome Browser in incognito mode
2. Open the developer tools 
3. under the light house tab click on generate report. 
4. Review results 

### developer site

<img width="786" alt="Screen Shot 2020-09-28 at 5 32 23 PM" src="https://user-images.githubusercontent.com/1395158/94496058-99bb6880-01b0-11eb-81cc-47459cc22dcc.png">

### opensource site

<img width="805" alt="Screen Shot 2020-09-28 at 5 31 02 PM" src="https://user-images.githubusercontent.com/1395158/94496030-88725c00-01b0-11eb-9ac4-2d74f2e398c5.png">

**Comment by jpvajda** [comment]
New reports as of Oct 23...

<img width="995" alt="Screen Shot 2020-10-23 at 11 30 28 AM" src="https://user-images.githubusercontent.com/1395158/97036771-8d16ff80-1525-11eb-8c64-864d82670800.png">


<img width="1057" alt="Screen Shot 2020-10-23 at 11 30 20 AM" src="https://user-images.githubusercontent.com/1395158/97036785-91431d00-1525-11eb-8ea0-62988d4291a3.png">

**Comment by caylahamann** [comment]
# Findings 
 
## Numbers are different for Mobile and Desktop 
### Mobile 
<img width="764" alt="Screen Shot 2020-11-10 at 11 23 01 AM" src="https://user-images.githubusercontent.com/38332422/98701302-211b0080-2347-11eb-9845-295be774283f.png">

### Desktop
<img width="742" alt="Screen Shot 2020-11-10 at 11 22 25 AM" src="https://user-images.githubusercontent.com/38332422/98701325-26784b00-2347-11eb-80ca-12a4901faabc.png">

## There are some main culprits for lower performance 
### Amplify Cache Policy 
* We can enable something called [performance mode](https://docs.aws.amazon.com/amplify/latest/userguide/ttl.html) on our main branch in order to ensure better caching. Changes will then take longer to appear on our main branch (10 minute deploy) but we would see better performance by keeping content cached at the end of the CDN for longer intervals. 
* Use custom headers. There are recommended headers for gatsby sites for caching static sites. We would need to add these under amplify in the custom headers section to set up proper HTTP caching. 

### Loading of NR1 Assets 
* This is currently being addressed in Jerel's PR to stitch the NR1 assets into GraphQL and then asynchronously load NR1 assets 

### Loading of other assets
* **Tessen**, this appears to still be happening and I'm not sure where we have landed on using tessen but it is taking up some of the payload 
* **Bizable**, We could asynchronously load these libraries as well? I'm not sure what bizable is being used for right now 
* **Google Fonts**, If we ensure that text remains visible during webfont load with a default backup text, then we wouldn't run into this issue.

### Further optimizations

We could use a library called [Guess.js](https://www.gatsbyjs.com/docs/optimizing-site-performance-with-guessjs/) to load our assets conditionally. Guess.js is able to determine which leverages Google Analytics data and machine learning to determine which pages a user is most likely to navigate to from the current page and only preload those resources.

**Comment by caylahamann** [comment]
* Make tickets out of these

**Comment by caylahamann** [comment]
Made follow up tickets in #954 #953 #952

**Comment by jpvajda** [comment]
@caylahamann thanks for all the work here, it's great to know what the root problems are on the performance lighthouse metric.

`Tessen` will eventually need to be used on the developer , oss and docs site, but i'm not sure how we are interacting with that service now, as we didn't finish the integration with it.

`Bizable` is used for marketing metrics, specifically tracking customer journey and was implemented on this issue: https://github.com/newrelic/developer-website/issues/803
