### ISSUE TITLE
[Dev Site] Content disappears when expanding screen while viewing the mobile navigation

### ISSUE THREAD

**Issue by djsauble** [newrelic/developer-website#957]
### Description

Page goes blank when increasing the width of the screen after opening the mobile navigation

### Steps to reproduce

1. Narrow the page until the hamburger appears
2. Click the hamburger
3. Widen the page until the mobile menu disappears and the remaining page is blank (header is still visible)

### Expected behavior

I expect the mobile menu to close and to be returned to the content.

### Screenshots

https://newrelic.enterprise.slack.com/files/W01AR8G3A04/F01EQBXAD0A/screen_recording_2020-11-13_at_9.35.29_am.mov

**Comment by jpvajda** [comment]
@zstix isn't this what you saw as well?

**Comment by zstix** [comment]
@jpvajda I've seen this before, but haven't filed any additional tickets for it.

**Comment by rudouglas** [comment]
@djsauble  @jpvajda It looks like this issue is now resolved, i've tested it on multiple browsers and the behaviour now seems to be that when you increase the width of the page again the Mobile Menu remains on screen until you `X` out of it:

https://user-images.githubusercontent.com/17122543/116418614-3a9c0000-a834-11eb-836e-2a7994e4fcd6.mov

**Comment by jpvajda** [comment]
Nice. closing.
